service: ${file(./package.json):name}

frameworkVersion: '3'

custom:
  DYNAMODB_USER_TABLE_NAME: 'Users-${self:provider.stage}'
  # configuring authorizer in provider.httpApi doesn't work and there are still open issue
  # should be added after serverless team fix this issue
  authorizer:
    type: request
    name: verifyToken
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  iam:
    role:
      name: my-app-function-role
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["usersTable", "Arn" ] }

  environment:
    REGION: ${self:provider.region}
    USER_TABLE_NAME: ${self:custom.DYNAMODB_USER_TABLE_NAME}

package:
  individually: true
  patterns:
    - '!build.mjs'
    - '!src/**'

functions:
  # authorizer
  verifyToken:
    handler: dist/functions/auth/verify-token.verifyToken

  healthCheck:
    handler: dist/functions/health-check.healthCheck
    events:
      - http:
          path: /health-check
          method: get
          authorizer: ${self:custom.authorizer}
  #Unprotected routes
  signUp:
    handler: dist/functions/auth/sign-up.signUp
    events:
      - http:
          path: /sign-up
          method: post
  signIn:
    handler: dist/functions/auth/sign-in.signIn
    events:
      - http:
          path: /sign-in
          method: post
  refresh:
    handler: dist/functions/auth/refresh.refresh
    events:
      - http:
          path: /refresh
          method: post

resources:
  - ${file(./src/resources/dynamoDbResource.yml)}
